import { Plant } from './plant';

export const DEFAULT_PLANT: Plant = {
  id: 1,
  isAlive: true,
  alive: 'Yes',
  HP: 10,
  humidity: 0,
  sunlight: 0,
  mood: ':(',
  name: 'Unknown',
  size: 1,
  owner: 'Unknown',
  species: 'Unknown',
  group: 'Unknown',
  imgUrl: '../assets/images/potnus.jpg',
  imgText: 'Alt text',
};

export const MOCK_PLANTS: Plant[] = [
  {
    id: 1,
    name: 'Potnus',
    size: 1,
    owner: 'Markus',
    species: 'Unknown',
    group: 'Gymnosperms',
    imgUrl: '../assets/images/potnus.jpg',
    imgText: 'Small boi',
    isAlive: true,
    alive: 'Yes',
    HP: 10,
    humidity: 0,
    sunlight: 0,
    mood: ':(',
  },
  {
    id: 2,
    name: 'Lykketrollet',
    size: 4,
    owner: 'Magnus',
    species: 'Unknown',
    group: 'Pteridophytes',
    imgUrl: '../assets/images/lykketrollet.jpg',
    imgText: 'Thicc boi',
    isAlive: true,
    alive: 'Yes',
    HP: 10,
    humidity: 0,
    sunlight: 0,
    mood: ':(',
  },
  {
    id: 3,
    name: 'Baby Alfred',
    size: 3,
    owner: 'Anton',
    species: 'Unknown',
    group: 'Gymnosperms',
    imgUrl: '../assets/images/baby_alfred.jpg',
    imgText: 'Baby boi',
    isAlive: true,
    alive: 'Yes',
    HP: 10,
    humidity: 0,
    sunlight: 0,
    mood: ':(',
  },
  {
    id: 4,
    name: 'Pilten',
    size: 2,
    owner: 'Jon',
    species: 'Unknown',
    group: 'Gymnosperms',
    imgUrl: '../assets/images/pilten.jpg',
    imgText: 'Sad boi :(',
    isAlive: true,
    alive: 'Yes',
    HP: 10,
    humidity: 0,
    sunlight: 0,
    mood: ':(',
  },
  {
    id: 5,
    name: 'Plutti',
    size: 5,
    owner: 'David',
    species: 'Unknown',
    group: 'Pteridophytes',
    imgUrl: '../assets/images/plutti.jpg',
    imgText: 'Fat boi',
    isAlive: true,
    alive: 'Yes',
    HP: 10,
    humidity: 0,
    sunlight: 0,
    mood: ':(',
  },
];
