import { Plant } from './plant';

export const DEFAULT_PLANT: Plant = {
  id: 0,
  isAlive: true,
  alive: 'Yes',
  HP: 10,
  humidity: 0,
  sunlight: 0,
  mood: ':(',
  name: 'Unknown',
  size: 1,
  owner: 'Unknown',
  species: 'Sunflower',
  family: 'Asteraceae',
  imgUrl: '../assets/images/unknown.jpg',
  imgText: 'Alt text',
};

export const MOCK_PLANTS: Plant[] = [
  {
    id: 0,
    name: 'Flavus',
    size: 1,
    owner: 'David',
    species: 'Sunflower',
    family: 'Asteraceae',
    imgUrl: '../assets/images/flavus.jpg',
    imgText: 'Yellowy',
    isAlive: true,
    alive: 'Yes',
    HP: 50,
    humidity: 30,
    sunlight: 360,
    mood: ':|',
  },
  {
    id: 1,
    name: 'Parvus',
    size: 4,
    owner: 'Sebastian',
    species: 'Sunflower',
    family: 'Asteraceae',
    imgUrl: '../assets/images/parvus.jpg',
    imgText: 'Smally',
    isAlive: true,
    alive: 'Yes',
    HP: 50,
    humidity: 30,
    sunlight: 360,
    mood: ':|',
  },
  {
    id: 2,
    name: 'Potnus',
    size: 3,
    owner: 'Magnus',
    species: 'Sunflower',
    family: 'Asteraceae',
    imgUrl: '../assets/images/potnus.jpg',
    imgText: 'Averagey',
    isAlive: true,
    alive: 'Yes',
    HP: 50,
    humidity: 30,
    sunlight: 360,
    mood: ':|',
  },
  {
    id: 3,
    name: 'Solus',
    size: 2,
    owner: 'Markus',
    species: 'Sunflower',
    family: 'Asteraceae',
    imgUrl: '../assets/images/solus.jpg',
    imgText: 'TryHardy',
    isAlive: true,
    alive: 'Yes',
    HP: 50,
    humidity: 30,
    sunlight: 360,
    mood: ':|',
  },
  {
    id: 4,
    name: 'Sune',
    size: 5,
    owner: 'Anton',
    species: 'Sunflower',
    family: 'Asteraceae',
    imgUrl: '../assets/images/sune.jpg',
    imgText: 'TryMorey',
    isAlive: true,
    alive: 'Yes',
    HP: 50,
    humidity: 30,
    sunlight: 360,
    mood: ':|',
  },
  {
    id: 5,
    name: 'Andreea',
    size: 5,
    owner: 'Andreea',
    species: 'Sunflower',
    family: 'Asteraceae',
    imgUrl: '../assets/images/andreea.jpg',
    imgText: 'Awayy',
    isAlive: true,
    alive: 'Yes',
    HP: 50,
    humidity: 30,
    sunlight: 360,
    mood: ':|',
  },
];
